# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `RailsEventStoreActiveRecord::MigrationGenerator`.
# Please instead update this file by running `bin/tapioca dsl RailsEventStoreActiveRecord::MigrationGenerator`.

class RailsEventStoreActiveRecord::MigrationGenerator
  sig { returns(::String) }
  def data_type; end
end
